import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"), updatedAt: text("updated_at") };
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull(), username: text("username"), role: text("role").notNull().default("buyer"), birthDate: text("birth_date"), country: text("country"), emailVerifiedAt: text("email_verified_at"), status: text("status").notNull().default("active"), ...timestamps }, (t) => [uniqueIndex("users_email_idx").on(t.email)]);
export const roles = sqliteTable("roles", { id: text("id").primaryKey(), name: text("name").notNull(), permissions: text("permissions").notNull().default("[]"), ...timestamps });
export const products = sqliteTable("products", { id: text("id").primaryKey(), title: text("title").notNull(), slug: text("slug"), type: text("type").notNull(), description: text("description"), price: real("price").notNull(), tag: text("tag").notNull(), tone: text("tone").notNull(), status: text("status").notNull().default("published"), accessPlan: text("access_plan"), ...timestamps }, (t) => [uniqueIndex("products_slug_idx").on(t.slug)]);
export const media = sqliteTable("media", { id: text("id").primaryKey(), productId: text("product_id").references(() => products.id), objectKey: text("object_key").notNull(), mimeType: text("mime_type").notNull(), isPreview: integer("is_preview", { mode: "boolean" }).notNull().default(false), ...timestamps });
export const plans = sqliteTable("plans", { id: text("id").primaryKey(), name: text("name").notNull(), price: real("price").notNull(), interval: text("interval").notNull(), benefits: text("benefits").notNull().default("[]"), status: text("status").notNull().default("active"), ...timestamps });
export const subscriptions = sqliteTable("subscriptions", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), planId: text("plan_id").notNull().references(() => plans.id), status: text("status").notNull(), startsAt: text("starts_at").notNull(), endsAt: text("ends_at"), providerRef: text("provider_ref"), ...timestamps });
export const orders = sqliteTable("orders", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id), total: real("total").notNull(), currency: text("currency").notNull().default("USD"), status: text("status").notNull(), paymentProvider: text("payment_provider"), affiliateId: text("affiliate_id"), ...timestamps });
export const orderItems = sqliteTable("order_items", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(() => orders.id), productId: text("product_id").notNull().references(() => products.id), unitPrice: real("unit_price").notNull(), ...timestamps });
export const favorites = sqliteTable("favorites", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), productId: text("product_id").notNull().references(() => products.id), ...timestamps });
export const affiliates = sqliteTable("affiliates", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), code: text("code").notNull(), status: text("status").notNull().default("pending"), commissionRate: real("commission_rate").notNull().default(.15), ...timestamps }, (t) => [uniqueIndex("affiliate_code_idx").on(t.code)]);
export const commissions = sqliteTable("commissions", { id: text("id").primaryKey(), affiliateId: text("affiliate_id").notNull().references(() => affiliates.id), orderId: text("order_id").notNull().references(() => orders.id), amount: real("amount").notNull(), status: text("status").notNull().default("pending"), ...timestamps });
export const supportTickets = sqliteTable("support_tickets", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id), name: text("name").notNull(), email: text("email").notNull(), category: text("category").notNull(), message: text("message").notNull(), status: text("status").notNull().default("open"), ...timestamps });
export const activityLog = sqliteTable("activity_log", { id: text("id").primaryKey(), actorId: text("actor_id").references(() => users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), metadata: text("metadata"), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP") });
